from numpy import array 

EUNIS_id_to_cls = {
    14: 'Surface standing waters',
    15: 'Surface running waters',
    16: 'Littoral zone of inland surface waterbodies',
    21: 'Mires, bogs and fens',
    23: 'Dry grasslands',
    24: 'Mesic grasslands',
    25: 'Seasonally wet and wet grasslands',
    26: 'Alpine and subalpine grasslands',
    31: 'Arctic, alpine and subalpine scrub',
    32: 'Temperate and mediterranean-montane scrub',
    40: 'Shrub plantations',
    41: 'Broadleaved deciduous woodland',
    43: 'Coniferous woodland',
    44: 'Mixed deciduous and coniferous woodland',
    45: 'Lines of trees, small anthropogenic woodlands',# recently felled woodland, early-stage woodland and coppice',
    47: 'Screes',
    48: 'Inland cliffs, rock pavements and outcrops',
    49: 'Snow or ice-dominated habitats',
    50: 'Miscellaneous inland habitats with very sparse or no vegetation',
    52: 'Arable land and market gardens',
    53: 'Cultivated areas of gardens and parks',
    54: 'Buildings of cities, towns and villages',
    55: 'Low density buildings',
    56: 'Extractive industrial sites',
    57: 'Transport networks and other constructed hard-surfaced areas'
 }

EUNIS_id_to_cls_id = {
    14: 0,      15: 1,      16: 2,      18: 3,
    21: 3,      23: 4,      24:5,      25: 6,
    26: 7,      31: 8,      32: 9,     40: 10,
    41: 11,     43: 12,     44: 13,     45: 14,
    47: 15,     48: 16,     49: 17,     50: 18,
    52: 19,     53: 20,     54: 21,     55: 22,
    56: 23,     57: 24,
 }
cls_id_to_EUNIS_id = {v: k for k, v in EUNIS_id_to_cls_id.items()}

EUNIS_id_to_short_labels  = {
    14: 'Lake',
    15: 'River',
    16: 'Littoral zone',
    21: 'Mires, bogs and fens',
    23: 'Dry grasslands',
    24: 'Mesic grasslands',
    25: 'Wet grasslands',
    26: 'Alpine grasslands',
    31: 'Alpine scrub',
    32: 'Temperate scrub',
    40: 'Shrub plantations',
    41: 'Broadleaved woodlands',
    43: 'Coniferous woodlands',
    44: 'Mixed woodlands',
    45: 'Anthropogenic woodlands',
    47: 'Screes',
    48: 'Ciffs and outcrops',
    49: 'Snow',
    50: 'Sparse vegetation',
    52: 'Arable land',
    53: 'Gardens and parks',
    54: 'Buildings',
    55: 'Low density buildings',
    56: 'Extractive  sites',
    57: 'Transport areas'
 }


# EUNIS_id_to_description :
EUNIS_id_to_description = {
 '14': 'Lakes, ponds and pools of natural origin containing fresh (i.e. nonsaline), brackish or salt water. Manmade freshwater bodies, including artificially created lakes, reservoirs and canals, provided that they contain seminatural aquatic communities.',
 '15': 'Running waters, including springs, streams and temporary water course',
 '16': 'Reedbeds and other water-fringing vegetation by lakes, rivers and streams;exposed bottoms of dried up rivers and lakes;rocks, gravel, sand and mud beside or in the bed of rivers and lakes.',
 '21': 'Wetlands, with the water table at or above ground level for at least half of the year, dominated by herbaceous or ericoid vegetation. Includes inland saltmarshes and waterlogged habitats where the groundwater is frozen. Excludes the water body and rock structure of springs  and waterlogged habitats dominated by trees or large shrubs. Note that habitats that intimately combine waterlogged mires and vegetation rafts with pools of open water are considered as complexes',
 '23': 'Well-drained or dry lands dominated by grass or herbs, mostly not fertilized and with low productivity. Included are Artemisia steppes. Excluded are dry mediterranean lands with shrubs of other genera where the shrub cover exceeds 10%;these are listed as garrigue .',
 '24': 'Lowland and montane mesotrophic and eutrophic pastures and hay meadows of the boreal, nemoral, warm-temperate humid and mediterranean zones. They are generally more fertile than dry grasslands , and include sports fields and agriculturally improved and reseeded pastures.',
 '25': 'Unimproved or lightly improved wet meadows and tall herb communities of the boreal, nemoral, warm-temperate humid, steppic and mediterranean zones.',
 '26': 'Primary and secondary grass- or sedge- dominated formations of the alpine and subalpine levels of boreal, nemoral, mediterranean, warm-temperate humid and Anatolian mountains. ',
 '31': 'Scrub occurring north of or above the climatic tree limit, but outside the permafrost zone. Scrub occurring close to but below the climatic tree limit, where trees are suppressed either by late-lying snow or by wind or repeated browsing.',
 '32': 'Shrub communities of nemoral affinities. They include deciduous and evergreen scrubs of the nemoral zone, and deciduous scrubs of the submediterranean and supramediterranean zones. Excluded are heathlands with dominant Ericaceae S4, and the typically mediterranean maquis S5, garrigue S6 and phrygana S7.',
 '40': 'Plantations of dwarf trees, shrubs, espaliers or perennial woody climbers, mostly cultivated for fruit or flower production, either intended to have permanent cover of woody plants when mature, or else for wood or small tree production with a regular whole-plant harvesting regime.',
 '41': 'Forest dominated by summer-green non-coniferous trees that drop their leaves for part of the year and goes dormant during cold weather. Includes forest with mixed evergreen and deciduous broadleaved trees, if the broadleaf deciduous cover exceeds that of evergreens. Old plantations which have many of the characteristics of natural or semi-natural forests are included, more intensively managed, and less natural, forests are included in vegetated man-made habitats.',
 '43': 'Forest dominated by coniferous trees, mainly evergreen (Abies, Cedrus, Picea, Pinus, Taxus, Cupressaceae) but also deciduous Larix. Includes forest with mixed coniferous and deciduous broadleaved trees, if the cover by coniferous trees exceeds that of deciduous trees. Old plantations which have many of the characteristics of natural or semi-natural forests are included, more intensively managed, and less natural, forests are included in vegetated man-made habitats.',
 '44': 'Forest and woodland of mixed broad-leaved deciduous or evergreen and coniferous trees of the nemoral, boreal, warm-temperate humid and mediterranean zones. They are mostly characteristic of the boreonemoral transition zone between taiga and temperate lowland deciduous forests, and of the montane level of the major mountain ranges to the south. Neither coniferous, nor broadleaved species account for more than 75% of the crown cover. Deciduous forests with an understorey of conifers or with a small admixture of conifers in the dominant layer are included in unit G1. Conifer forests with an understorey of deciduous trees or with a small admixture of deciduous trees in the dominant layer are included in unit G3.',
 '45': 'Stands of trees greater than 5 m in height or with the potential to achieve this height, either in more or less continuous narrow strips or in small (less than about 0.5 ha) plantations or small (less than about 0.5 ha) intensively-managed forests. Forests and coppice that is temporarily in a successional or non-forest stage but which can be expected to develop into forest in the future. Excludes parkland (R71, R72).',
 '47': 'Accumulations of boulders, stones, rock fragments, pebbles, gravels or finer material, of non-aeolian and non-fluvial depositional origin, unvegetated, occupied by lichens or mosses, or colonized by sparse herbs or shrubs. Included are screes and scree slopes produced by slope processes, moraines and drumlins originating from glacial deposition, sandar, eskers and kames resulting from fluvio-glacial deposition, block slopes, block streams and block fields constructed by periglacial depositional processes of downslope mass movement, ancient beach deposits constituted by former coastal constructional processes. Deposits originating from aeolian depositional processes (dunes) or from eruptive volcanic activity are not included;they are included in U5 and U6 respectively. High mountain, boreal and mediterranean unstable screes are colonized by highly specialised plant communities. They or their constituting species may also inhabit moraines and other depositional debris accumulations in the same areas. A very few communities form in lowland areas elsewhere',
 '48': 'Unvegetated, sparsely vegetated, and bryophyte  or lichen vegetated cliffs, rock faces and rock pavements, not presently adjacent to the sea, and not resulting from recent volcanic activity. Parts of seacliffs free from the influence of wave or wind transported marine salt are included. Rock accumulations resulting from depositional processes are excluded and listed under U2 or U5',
 '49': 'High mountain zones and high latitude land masses occupied by glaciers or by perennial snow. They may be inhabited by algae and invertebrates',
 '50': 'Miscellaneous bare habitats, including glacial moraines, freeze-thaw features, inland sand dunes, burnt ground and trampled areas. Vegetation, if present, is dominated by algae, lichens or bryophytes, with vascular plants absent or very sparse',
 '52': 'Croplands planted for annually or regularly harvested crops other than those that carry trees or shrubs. They include fields of cereals, of sunflowers and other oil seed plants, of beets, legumes, fodder, potatoes and other forbs. Croplands comprise intensively cultivated fields as well as traditionally and extensively cultivated crops with little or no chemical fertilisation or pesticide application. Faunal and floral quality and diversity depend on the intensity of agricultural use and on the presence of borders of natural vegetation between fields',
 '53': 'Cultivated areas of small-scale and large-scale gardens, including kitchen gardens, ornamental gardens and small parks in city squares. Excludes allotment gardens.',
 '54': 'Buildings in built-up areas where buildings, roads and other impermeable surfaces occupy at least 30% of the land. Includes agricultural building complexes where the built area exceeds 1 ha.',
 '55': 'Buildings in rural and built-up areas where buildings, roads and other impermeable surfaces are at a low density, typically occuping less than 30% of the ground. Excludes agricultural building complexes where the built area exceeds 1 ha.',
 '56': 'Sites in which minerals are extracted. Includes quarries, open-cast mines and active underground mines.',
 '57': 'Includes roads, car parks, railways, paved footpaths and hard-surfaced areas of airports, water ports and recreational areas.'
 }


# official RGB color map  from EUNIS 
sns_eunis_palette = {
  11: array([0.90196078, 0.90196078, 0.90196078]),
  12: array([0.78431373, 0.78431373, 0.78431373]),
  13: array([0.66666667, 0.66666667, 0.66666667]),
  14: array([0.50196078, 0.94901961, 0.90196078]),
  15: array([0.        , 0.8       , 0.94901961]),
  16: array([0. , 0.8, 0.6]),
  17: array([0.25098039, 0.19215686, 0.31764706]),
  18: array([0.37647059, 0.28627451, 0.47843137]),
  19: array([0.69411765, 0.62745098, 0.78039216]),
  20: array([0.8       , 0.75294118, 0.85490196]),
  21: array([0.85490196, 0.93333333, 0.95294118]),
  22: array([0.71764706, 0.87058824, 0.90980392]),
  23: array([0.94117647, 0.94117647, 0.58823529]),
  24: array([0.90196078, 0.90196078, 0.30196078]),
  25: array([0.8       , 0.94901961, 0.30196078]),
  26: array([0.6, 1. , 0.6]),
  28: array([0.8, 1. , 1. ]),
  29: array([0.94901961, 0.8       , 0.65098039]),
  30: array([0.59215686, 0.27843137, 0.02352941]),
  31: array([0.88627451, 0.41960784, 0.03921569]),
  32: array([0.98039216, 0.74901961, 0.56078431]),
  33: array([0.98823529, 0.83529412, 0.70588235]),
  34: array([0.99215686, 0.91372549, 0.85098039]),
  35: array([0.85490196, 0.93333333, 0.95294118]),
  36: array([0.71764706, 0.87058824, 0.90980392]),
  37: array([0.57254902, 0.80392157, 0.8627451 ]),
  38: array([0.19215686, 0.78431373, 0.60784314]),
  40: array([0.90196078, 0.50196078, 0.        ]),
  41: array([0.50196078, 1.        , 0.        ]),
  42: array([0.90196078, 0.65098039, 0.        ]),
  43: array([0.        , 0.65098039, 0.        ]),
  44: array([0.30196078, 1.        , 0.        ]),
  45: array([0.30980392, 0.38431373, 0.15686275]),
  47: array([0.94901961, 0.94901961, 0.94901961]),
  48: array([0.8, 0.8, 0.8]),
  49: array([1., 1., 1.]),
  50: array([0.8, 1. , 0.8]),
  52: array([1.        , 1.        , 0.65882353]),
  53: array([1., 1., 0.]),
  54: array([1., 0., 0.]),
  55: array([1.        , 0.49019608, 0.49019608]),
  56: array([0.65098039, 0.        , 0.8       ]),
  57: array([1.        , 0.33333333, 0.        ]),
  58: array([0.90196078, 0.90196078, 1.        ]),
  59: array([0.65098039, 0.30196078, 0.        ])}


sns_eunis_palette_w_classnames = {EUNIS_id_to_cls[x] : y for x,y in sns_eunis_palette.items() if x in EUNIS_id_to_cls.keys()}