# a collection of prompts
EUNIS_id_to_cls = {
    14: 'Surface standing waters',
    15: 'Surface running waters',
    16: 'Littoral zone of inland surface waterbodies',
    21: 'Mires, bogs and fens',
    23: 'Dry grasslands',
    24: 'Mesic grasslands',
    25: 'Seasonally wet and wet grasslands',
    26: 'Alpine and subalpine grasslands',
    31: 'Arctic, alpine and subalpine scrub',
    32: 'Temperate and mediterranean-montane scrub',
    40: 'Shrub plantations',
    41: 'Broadleaved deciduous woodland',
    43: 'Coniferous woodland',
    44: 'Mixed deciduous and coniferous woodland',
    45: 'Lines of trees, small anthropogenic woodlands',# recently felled woodland, early-stage woodland and coppice',
    47: 'Screes',
    48: 'Inland cliffs, rock pavements and outcrops',
    49: 'Snow or ice-dominated habitats',
    50: 'Miscellaneous inland habitats with very sparse or no vegetation',
    52: 'Arable land and market gardens',
    53: 'Cultivated areas of gardens and parks',
    54: 'Buildings of cities, towns and villages',
    55: 'Low density buildings',
    56: 'Extractive industrial sites',
    57: 'Transport networks and other constructed hard-surfaced areas'
 }

aerial_dict = {x : 'An aerial image of a ' +y for x,y in EUNIS_id_to_cls.items()}
rs_dict = {x : 'A remote sensing image of a ' +y for x,y in EUNIS_id_to_cls.items()}
sat_dict = {x : 'A satellite image of a ' +y for x,y in EUNIS_id_to_cls.items()}


EUNIS_id_2_ollama_descr={
 14: ['Surface standing water in temperate mixed forests exhibit dense vegetation and minimal algae growth, often with scattered tree roots visible on the surface.',
  'In the Carpathian Mountains, surface standing waters in montane coniferous forests display a mix of slow-moving and stagnant water bodies, often with submerged logs.',
  'Freshwater lakes in boreal coniferous forests have high levels of nutrient-rich sediments and frequent algae blooms, giving them a bright green appearance.',
  'Surface standing waters in Mediterranean maquis habitats are characterized by low vegetation cover, sparse aquatic life, and high salinity levels.',
  'Surface standing water in Arctic tundra exhibit short vegetation growths, with minimal macrophytes present due to the harsh climate conditions.',
  'Surface standing water in deciduous mixed forests display a mix of slow-moving and stagnant water bodies, often with submerged branches.',
  'Freshwater lakes in alpine meadows have steep shorelines, clear water, and frequent aquatic life, reflecting the high productivity of these ecosystems.',
  "In the UK's upland areas, surface standing waters in heathlands have low vegetation cover, sparse aquatic life, and a distinct acidic pH.",
  'Surface standing water in riparian zones along European rivers often display dense vegetation growths, with frequent algae blooms due to nutrient-rich sediments.',
  "In the Iberian Peninsula's Atlantic coast, surface standing waters in salt marshes are characterized by high salinity levels, sparse aquatic life, and complex network of channels.",
  'Freshwater lakes in alpine grasslands have steep shorelines, clear water, and frequent aquatic life, reflecting the unique glacial history of these regions.',
  'Surface standing water in boreal boreal forests exhibit dense vegetation cover, with minimal algae growth due to low nutrient levels.',
  "In Eastern Europe's temperate forests, surface standing waters display a mix of slow-moving and stagnant water bodies, often with submerged tree trunks.",
  'Freshwater lakes in subarctic tundra have high levels of nutrient-rich sediments, frequent algae blooms, and a distinct acidic pH due to permafrost influence.',
  'Surface standing water in Mediterranean coastal dunes exhibit low vegetation cover, sparse aquatic life, and a clear distinction between the water surface and the surrounding sand.',
  "In Western Europe's heathlands, surface standing waters often display dense vegetation growths, with frequent algae blooms due to nutrient-rich sediments.",
  'Freshwater lakes in subalpine coniferous forests have steep shorelines, clear water, and frequent aquatic life, reflecting the high productivity of these ecosystems.',
  'Surface standing water in boreal coniferous forests exhibit dense vegetation cover, with minimal algae growth due to low nutrient levels and cold temperatures.',
  "In Northern Europe's wetlands, surface standing waters display a mix of slow-moving and stagnant water bodies, often with submerged vegetation growths.",
  'Freshwater lakes in temperate mixed forests have moderate levels of nutrient-rich sediments, frequent algae blooms, and a distinct greenish tint due to dissolved nutrients.',
  'Surface standing water in alpine tundra exhibit short vegetation growths, with minimal macrophytes present due to the harsh climate conditions and permafrost influence.',
  "In Southern Europe's dry grasslands, surface standing waters often display low vegetation cover, sparse aquatic life, and high salinity levels due to aridification.",
  'Freshwater lakes in temperate deciduous forests have moderate levels of nutrient-rich sediments, frequent algae blooms, and a distinct brownish tint due to tannins released by trees.',
  "Surface standing water in Eastern Europe's pine forests exhibit dense vegetation cover, with minimal algae growth due to low nutrient levels and acidic pH.",
  "In Northern Europe's boreal coniferous forests, surface standing waters display a mix of slow-moving and stagnant water bodies, often with submerged tree roots visible on the surface."],
 15: ['Surface running waters refer to rivers, streams, and creeks that flow over land and have no direct connection to the ocean.',
  'These water bodies are typically characterized by a slow to moderate current speed and a narrow depth range.',
  'Surface running waters often exhibit high levels of turbulence and sediment transport due to their proximity to land surfaces.',
  'The biodiversity associated with surface running waters is diverse, including aquatic plants, insects, fish, and mammals.',
  'Riverbanks and stream beds are typically lined with vegetation such as willows, alders, and grasses.',
  'Surface running waters can be influenced by various land cover types, including agricultural fields, forests, and urban areas.',
  'The climate of surface running waters is often controlled by nearby topography and microclimates.',
  'Stream beds and river channels may exhibit meandering or straight courses, depending on geological processes.',
  'Surface running waters can carry a wide range of sediments, from fine-grained silt to coarse gravel and boulders.',
  'Aquatic life in surface running waters includes fish species such as trout, grayling, and salmon.',
  'Vegetation along riverbanks can form dense stands of riparian vegetation, including willow, alder, and cottonwood trees.',
  'Surface running waters may experience changes in flow regimes due to seasonal variations, human activities, or climate change.',
  'The morphology of surface running waters is shaped by factors such as gradient, slope, and channel width.',
  'Aquatic insects in surface running waters include mayflies, caddisflies, and stoneflies.',
  'Surface running waters can be affected by nearby water treatment plants, sewage outfalls, or other anthropogenic sources.',
  'The aquatic food web in surface running waters is complex, involving primary producers, zooplankton, and a variety of fish species.',
  'Vegetation along streams and rivers may exhibit erosion and deposition patterns due to flow velocity and sediment transport.',
  'Surface running waters can be impacted by agricultural runoff, including fertilizers, pesticides, and sediments.',
  'The hydrology of surface running waters is influenced by factors such as precipitation, evapotranspiration, and groundwater recharge.',
  'Aquatic mammals in surface running waters include otters, beavers, and muskrats.',
  'Surface running waters may experience changes in water temperature due to seasonality or human activities.',
  'The riparian zone of surface running waters is an ecologically important habitat for plants and animals.',
  'Vegetation along riverbanks can provide shade, shelter, and food sources for aquatic life.',
  'Surface running waters can be affected by climate change, including changes in temperature, precipitation, and drought frequency.',
  'Aquatic algae in surface running waters play a crucial role in primary production and water quality.'],
 16: ['The littoral zone of an inland surface waterbody is the area where the shoreline meets the land, characterized by a mix of aquatic and terrestrial features.',
  "This zone is typically narrow, ranging from 10-100 meters in width, depending on the waterbody's morphology and surrounding topography.",
  'Inland littorals often feature a unique combination of aquatic vegetation, such as cattails, bulrushes, and sedges, which are adapted to survive in brackish or freshwater environments.',
  'The littoral zone is home to a diverse array of plant species, including emergent wetlands like cattail marshes and cordgrass bars.',
  'Aquatic animals, such as fish, crayfish, and frogs, are abundant in this zone, taking advantage of the mix of water and land resources.',
  'Inland littorals can be dominated by terrestrial plants like grasses, sedges, or shrubs, which provide habitat for a range of wildlife.',
  "The zone's unique microclimate supports a variety of unique plant communities, such as riparian forests along rivers or streams.",
  'Aerial images may reveal the presence of aquatic features like sandbars, mudflats, or wet meadows, particularly in areas with high water tables.',
  'Human activities, such as agriculture, urbanization, and infrastructure development, can significantly impact inland littorals, leading to habitat loss and degradation.',
  "The zone's biodiversity is influenced by factors like water quality, substrate type, and surrounding land use patterns.",
  'Inland littorals may exhibit characteristics of a "floodplain" or " flood-meadow", where periodic flooding supports unique plant communities.',
  'Vegetation in this zone can be dominated by species adapted to high water tables, such as cattails or sedges.',
  "The presence of aquatic features like submerged logs or sunken tree trunks can be visible in aerial images, highlighting the zone's complex morphology.",
  'Inland littorals often feature a unique "shoreline" that blends with the surrounding terrain, making it difficult to distinguish from adjacent land cover.',
  'Aquatic animals may congregate around features like submerged islands or weed beds, providing habitat and feeding grounds.',
  'Vegetation in this zone can be influenced by factors like salinity, nutrient availability, and water temperature.',
  'The littoral zone supports a range of unique animal communities, including insects, crustaceans, and fish that are adapted to brackish environments.',
  "Human impact on inland littorals can lead to changes in water quality, substrate type, and surrounding land use patterns, altering the zone's biodiversity.",
  'Aerial images may reveal the presence of "riparian forests" along rivers or streams, which support unique plant communities.',
  'Inland littorals can be influenced by factors like climate change, leading to shifts in vegetation composition and animal populations.',
  "The zone's unique microclimate supports a range of epiphytic plants, such as mosses, lichens, or algae, which grow on aquatic features like rocks or trees.",
  'Aquatic animals may use the littoral zone as a "transit corridor" between freshwater and brackish environments, facilitating migration and dispersal.',
  'Inland littorals can be characterized by unique landforms like "mudflats", "sandbars", or "wet meadows", which support unique plant communities.',
  'Vegetation in this zone can be influenced by factors like soil type, nutrient availability, and water table depth.',
  'Aerial images may reveal the presence of "wetland edges" or "shallow water bodies" along rivers or streams, supporting unique plant communities.'],
 21: ['A mire is a type of wetland characterized by acidic, oxygen-poor conditions, typically found in low-lying areas with poor drainage.',
  'Mires often have a layer of peat, a accumulation of partially decayed plant matter that can be several meters thick.',
  'The surface of a mire may appear as a network of shallow pools and channels, reflecting the presence of acidic water.',
  'Fen meadows are characterized by a mix of grasses, sedges, and wildflowers, often with a dominant vegetation type such as quaking reed or cotton grass.',
  'Bogs tend to be more oligotrophic (nutrient-poor) than fens, resulting in a lower diversity of plant species.',
  'The peat layer in bogs can be up to 10 meters thick, making them one of the oldest living things on Earth.',
  'Mires can be found in a variety of landscapes, including river floodplains, coastal areas, and heathlands.',
  'The water table in mires is typically low, resulting in a distinctive "waterlogged" appearance.',
  'Fen edges often have a characteristic "fen boundary", marked by a zone of vegetation transition from fen to adjacent land cover.',
  'Mire surfaces may be adorned with a variety of aquatic plants, including carnivorous plants such as sundews and pitcher plants.',
  'The atmospheric deposition of nitrogen and sulfur compounds can lead to the formation of distinctive mire pools or "fen puddles".',
  'Peat extraction is a common human activity in mires, with large areas being drained for agriculture or urban development.',
  'Mires provide important habitat for rare and threatened species, such as the marsh fritillary butterfly.',
  'Fen meadows can be managed through regular burns, which help to maintain vegetation diversity and prevent invasive species.',
  'Bogs often have a "blanket bog" character, where the surface is covered by a layer of sphagnum moss.',
  "The mire's hydrology is influenced by rainfall, groundwater flow, and nutrient inputs from surrounding land cover.",
  'Mires can be classified as either acidic or alkaline based on their pH levels, which affect the types of plants that thrive in them.',
  'Fen edges may exhibit a "fen gap", where vegetation transitions rapidly to adjacent land cover, creating a mosaic landscape.',
  'Peat harvesting is regulated by law in many countries due to its importance for carbon sequestration and global climate change mitigation.',
  'Mires can act as natural filters, capturing pollutants and sediments from the surrounding watercourse.',
  'The atmospheric conditions around mires can lead to the formation of distinctive "mire fog" or "fen mist".',
  'Bogs may exhibit a " bog pool", a large depression with standing water that is often home to unique aquatic species.',
  'Fen meadows can be managed through rotational grazing, which helps to maintain vegetation diversity and prevent soil erosion.',
  'Mires provide important ecosystem services, including carbon sequestration, water filtration, and habitat provision for biodiversity.',
  'The peat layer in mires can be used as a natural indicator of past climate conditions, such as the amount of rainfall or temperature.'],
 23: ['Dry grasslands are temperate to subtropical regions with low rainfall and vegetation dominated by grasses.',
  'Characterized by sparse vegetation, dry grasslands exhibit a mosaic of bare ground and scattered vegetation patches.',
  'Dominated by herbaceous species, dry grasslands often feature a variety of grass types, including tall grasses and short grasses.',
  'The terrain in dry grasslands is typically flat to gently sloping, with few trees or shrubs.',
  "Vegetation cover ranges from 20% to 50%, depending on the region's climate and rainfall.",
  'Dry grasslands often exhibit a mix of sand, clay, and gravel soils.',
  'These regions are characterized by limited vegetation diversity due to harsh climate conditions.',
  'Wildlife in dry grasslands is generally adapted to arid environments, with species such as gazelles and gerbils found here.',
  'Dry grasslands can be found in various parts of Europe, including the Mediterranean region and southern France.',
  'The landscape in these regions is often dotted with rocky outcrops, hills, or sandy ridges.',
  'Vegetation patches are often irregularly shaped, reflecting the impact of grazing animals on the terrain.',
  'Dry grasslands exhibit a range of soil types, from sandy loams to stony soils.',
  'These areas receive less than 600 mm (24 in) of rainfall annually, which limits plant growth and diversity.',
  'The climate in dry grasslands is typically hot during the summer months, with cold winters.',
  'Vegetation height varies greatly, ranging from a few centimeters to several meters tall.',
  'The terrain is often fragmented by artificial boundaries such as roads and fences.',
  'Dry grasslands can be affected by human activities such as overgrazing and drainage of water bodies.',
  'Some dry grasslands are characterized by the presence of scrub vegetation, which includes small trees and shrubs.',
  'The landscape in these regions is often dominated by a few large tree species, such as pine or oak.',
  'Dry grasslands can be found at various elevations, from sea level to mountainous terrain.',
  "Vegetation cover in dry grasslands varies greatly depending on the region's microclimate and rainfall patterns.",
  'The terrain in these regions is often punctuated by small lakes or wetlands, which support aquatic life.',
  'Dry grasslands can be affected by periodic droughts, which impact plant growth and wildlife populations.',
  'Some dry grasslands are characterized by a mix of different vegetation types, including grasses, shrubs, and trees.',
  'The landscape in these regions is often shaped by human activities such as agriculture and livestock grazing.'],
 24: ['Mesic grasslands are temperate grassland ecosystems characterized by moderate precipitation, typically between 500-1500 mm per year.',
  'These regions exhibit a mix of warm-season and cool-season grasses, resulting in a diverse array of vegetation.',
  'Mesic grasslands often feature scattered trees, such as oak, beech, or pine, which can provide habitat for various wildlife species.',
  'The presence of wet meadows and shallow lakes is common in mesic grasslands, supporting aquatic life.',
  'Soils in these regions are typically fertile and well-drained, allowing for dense vegetation growth.',
  'Mesic grasslands are often dominated by tallgrass species, such as big bluestem or switchgrass.',
  'The transition zones between grassland and adjacent habitats, like forests or wetlands, can be critical areas for biodiversity.',
  'Migratory bird species frequently inhabit mesic grasslands during their spring and fall migrations.',
  'Fire is a natural disturbance mechanism in these ecosystems, shaping vegetation structure and promoting regeneration.',
  'Mesic grasslands are commonly found in temperate regions with mild winters and warm summers.',
  'They can be classified into several subtypes, such as prairie, savanna, or mixed grassland.',
  'The presence of wildflowers, like coneflowers or black-eyed Susans, adds visual interest to these ecosystems.',
  'Grazing animals, including deer and bison, are often found in mesic grasslands.',
  'Agricultural activities, such as farming and ranching, can significantly alter the composition and structure of these ecosystems.',
  'Mesic grasslands provide important ecosystem services, including carbon sequestration and water filtration.',
  'The diversity of plant species in mesic grasslands supports a wide range of herbivores, from insects to large mammals.',
  'Vegetation height varies across different areas of the mesic grassland, with some patches featuring short-stemmed grasses.',
  'Oak savannas are a subtype of mesic grasslands characterized by an abundance of oak trees.',
  'Mesic grasslands can be influenced by human activities, such as road construction and urbanization.',
  'Natural disturbances, like floods or droughts, can significantly impact the composition and structure of these ecosystems.',
  'The presence of wetlands and aquatic vegetation is common in mesic grasslands, supporting a diverse array of aquatic life.',
  'Grassland-dwelling insect species, such as bees and butterflies, are often found in mesic grasslands.',
  'Fire management practices can be used to maintain the health and diversity of these ecosystems.',
  'Human impact on mesic grasslands is evident in altered land use patterns, such as intensive farming or overgrazing.',
  'These ecosystems are valuable for their ecological, economic, and cultural significance, supporting biodiversity and natural resources.'],
 25: ['Seasonally wet and wet grasslands (European Union): Characterized by temporary waterlogging, these grasslands typically exhibit patchy vegetation cover and variable land use patterns.',
  'Wet meadow (Europe): Dominated by aquatic plants such as sedges and rushes, this type of wetland is often characterized by shallow pools and slow-moving streams.',
  'Marsh grassland (Europe): Characterized by a mix of herbaceous and woody vegetation, these grasslands typically display a mosaic of different plant communities and water bodies.',
  'Wet fen (European Union): A type of seasonal wetland dominated by aquatic plants, fens are often characterized by slow-moving streams and a lack of tree cover.',
  'Marshy meadow (Europe): A transition zone between grasslands and wetlands, marshy meadows typically exhibit a mix of herbaceous and woody vegetation and variable water levels.',
  'Seasonal fen (European Union): Characterized by a mix of aquatic and terrestrial plant species, seasonal fens often display a mosaic of different habitats and land use patterns.',
  'Wet heathland (Europe): A type of grassland dominated by acid-loving plants such as heather and gorse, wet heathlands are often characterized by slow-moving streams and poor soil quality.',
  'Marshy grassland (European Union): Characterized by a mix of herbaceous and woody vegetation, marshy grasslands typically display a mosaic of different plant communities and water bodies.',
  'Seasonal meadow (Europe): A type of grassland that exhibits temporary waterlogging, seasonal meadows are often characterized by patchy vegetation cover and variable land use patterns.',
  'Wet woodland edge (European Union): The boundary between a forest and a wetland or grassland, these areas typically exhibit a mix of tree and herbaceous vegetation and variable water levels.',
  'Marshy sedge fen (Europe): A type of seasonal wetland dominated by aquatic plants such as sedges, marshy sedge fens are often characterized by shallow pools and slow-moving streams.',
  'Wet grassland with mire (European Union): Characterized by a mix of herbaceous and woody vegetation, these grasslands typically display a mosaic of different plant communities and water bodies.',
  'Seasonal floodplain meadow (Europe): A type of grassland that exhibits temporary waterlogging during periods of high rainfall or flooding, seasonal floodplain meadows are often characterized by patchy vegetation cover and variable land use patterns.',
  'Marshy reed bed (Europe): A type of wetland dominated by aquatic plants such as reeds and rushes, marshy reed beds are often characterized by shallow pools and slow-moving streams.',
  'Wet heath with mire (European Union): The boundary between a heathland and a wetland or grassland, these areas typically exhibit a mix of tree and herbaceous vegetation and variable water levels.',
  'Seasonal seep (Europe): A type of wetland that exhibits temporary waterlogging during periods of high rainfall or flooding, seasonal seeps are often characterized by shallow pools and slow-moving streams.',
  'Wet sedge fen with mire (European Union): Characterized by a mix of aquatic and terrestrial plant species, these fens are often displayed a mosaic of different habitats and land use patterns.',
  'Marshy grassland with wet meadow (Europe): A type of grassland that exhibits a mix of herbaceous and woody vegetation, marshy grasslands with wet meadows are often characterized by patchy vegetation cover and variable water levels.',
  'Seasonal fen with reed bed (European Union): Characterized by a mix of aquatic and terrestrial plant species, these fens are often displayed a mosaic of different habitats and land use patterns.',
  'Wet woodland edge with mire (European Union): The boundary between a forest and a wetland or grassland, these areas typically exhibit a mix of tree and herbaceous vegetation and variable water levels.',
  'Marshy sedge fen with seasonal seep (Europe): A type of seasonal wetland dominated by aquatic plants such as sedges, marshy sedge fens are often characterized by shallow pools and slow-moving streams.',
  'Wet grassland with seasonally flooded meadow (European Union): Characterized by a mix of herbaceous and woody vegetation, these grasslands typically display a mosaic of different plant communities and water bodies.',
  'Seasonal floodplain meadow with reed bed (Europe): A type of grassland that exhibits temporary waterlogging during periods of high rainfall or flooding, seasonal floodplain meadows are often characterized by patchy vegetation cover and variable land use patterns.',
  'Marshy heath with mire (European Union): The boundary between a heathland and a wetland or grassland, these areas typically exhibit a mix of tree and herbaceous vegetation and variable water levels.',
  'Wet sedge fen with seasonal seep and reed bed (European Union): Characterized by a mix of aquatic and terrestrial plant species, these fens are often displayed a mosaic of different habitats and land use patterns.'],
 26: ['Alpine grasslands are temperate grassland communities found at high elevations, typically above 2,500 meters.',
  'Characterized by low vegetation density and limited tree cover, these grasslands dominate the landscape with a sea of green.',
  'The terrain is often rocky outcrops, scree slopes, and talus fields, which provide habitat for unique alpine plants.',
  'Alpine grasslands are home to a diverse range of flora, including succulent plants, mosses, and lichens.',
  'The grassland layer is dominated by low-growing species such as gentians, saxifrages, and primulas.',
  'Wildflowers such as edelweiss and alpenrose are common in these areas, adding splashes of color to the landscape.',
  'Alpine grasslands often have a limited understory due to the harsh climate and poor soil quality.',
  'The dominant tree species in subalpine zones include spruce, fir, and pine, which form a canopy layer above the grassland.',
  'These areas are typically cold and dry, with short growing seasons and limited precipitation.',
  'Alpine grasslands can be found on well-drained soils, such as limestone or granite outcrops.',
  'The landscape is often dominated by rocky outcrops, scree slopes, and talus fields, which provide habitat for unique alpine plants.',
  'In subalpine zones, the transition from grassland to forest occurs gradually, with shrubs and trees becoming more common.',
  'Alpine grasslands can be found on a variety of terrain types, including rocky outcrops, scree slopes, and snowfields.',
  'These areas are often characterized by a lack of tree cover, with only scattered individual trees or small groups.',
  'The soil in alpine grasslands is often poor in nutrients, leading to a dominance of low-growing plants.',
  'Alpine grasslands can be found on the north-facing slopes of mountains, where the climate is cooler and more humid.',
  'These areas are often home to unique alpine wildlife, such as the snow leopard or ibex.',
  'The landscape is dominated by a variety of rock types, including granite, basalt, and limestone.',
  'Alpine grasslands can be found in mountainous regions with steep slopes and rugged terrain.',
  'The vegetation in these areas is often limited to low-growing species that are adapted to the harsh climate.',
  'In subalpine zones, the transition from grassland to forest occurs gradually, with shrubs and trees becoming more common.',
  'Alpine grasslands can be affected by human activities such as mining, logging, and tourism.',
  'The landscape is often characterized by a lack of tree cover, with only scattered individual trees or small groups.',
  'These areas are often home to unique alpine microclimates, which support a variety of rare plant species.',
  'Alpine grasslands can be found in mountainous regions with limited accessibility, making them vulnerable to human impact.'],
 31: ['Arctic Scrub: A sparse, low-growing vegetation community found in the Arctic tundra, characterized by prostrate shrubs such as dwarf willow (Salix herbacea) and cotton grass (Eriophorum angustifolium).',
  'Alpine Scrub: A type of vegetation found on mountain slopes and rocky outcrops at high elevations, often dominated by low-growing shrubs like rhododendron (Rhododendron hirsutum) and bilberry (Vaccinium myrtillus).',
  'Subalpine Scrub: A transitional zone between alpine and montane vegetation, characterized by a mix of shrubs and herbaceous plants like gentian (Gentiana acaulis) and arctic poppy (Papaver radicatum).',
  'Arctic Scrub mosaic: A patchwork of different scrub species, often found in areas with poor soil quality or high winds, featuring plants like cotton grass, dwarf willow, and lichens.',
  'Alpine Scrub edges: The boundary between alpine scrub and surrounding vegetation, characterized by a mix of shrubs and herbaceous plants that are adapted to the specific conditions on each side of the edge.',
  'Subalpine Scrub lineages: A group of plant species that have evolved in response to the unique conditions of the subalpine zone, often featuring adaptations like early frost tolerance or high-altitude photosynthesis.',
  'Arctic Scrub microhabitats: Small areas within the scrub community, such as under rocks or logs, where specialized plants like lichens and mosses can thrive in a variety of conditions.',
  'Alpine Scrub vegetation structure: Characterized by a dense mat of low-growing shrubs, often forming a "carpet" that shades out competing plant species.',
  'Subalpine Scrub disturbance regimes: Shaped by natural events like rockfall, landslides, and windstorms, which create patches of open ground where new vegetation can establish itself.',
  'Arctic Scrub soil chemistry: Often acidic and nutrient-poor, with a high concentration of minerals like sodium and potassium that are adapted to the harsh arctic conditions.',
  'Alpine Scrub canopy layer: Composed primarily of low-growing shrubs, which provide shade and protect underlying vegetation from extreme temperatures and weather conditions.',
  'Subalpine Scrub fog ecology: Characterized by the presence of fog, which provides moisture for plants like arctic poppy and gentian that are adapted to high-humidity environments.',
  'Arctic Scrub permafrost: Ground that remains frozen year-round, affecting plant growth patterns and species composition in areas with persistent frost.',
  'Alpine Scrub snow cover: A seasonal feature of the alpine environment, providing insulation for plants like rhododendron and bilberry during periods of extreme cold.',
  'Subalpine Scrub glacial features: Shaped by ancient glaciers that scoured out valleys and created unique landforms like U-shaped valleys and glacial lakes.',
  'Arctic Scrub phenology: Characterized by a delayed growth season, with many plants emerging in late summer or early fall to take advantage of the short arctic growing season.',
  'Alpine Scrub species distribution: Limited to specific elevations and latitudes, often featuring plant species that have adapted to local conditions over thousands of years.',
  'Subalpine Scrub fire regimes: Shaped by lightning strikes and human activity, which create patches of open ground where vegetation can regenerate after fires.',
  'Arctic Scrub land use history: Characterized by a long history of human presence, including hunting, gathering, and subsistence activities that have shaped the plant communities in these areas.',
  'Alpine Scrub biogeochemical cycles: Involved in the exchange of nutrients between plants, animals, and microorganisms, with unique patterns of element cycling that reflect local conditions.',
  'Subalpine Scrub geomorphology: Characterized by a complex landscape of glacial features, rockfalls, and landslides that create diverse habitats for plant species.',
  'Arctic Scrub soil moisture regimes: Often characterized by high variability in moisture levels, with plants like cotton grass adapting to the unpredictable conditions.',
  'Alpine Scrub wildlife ecology: Features a diverse array of animals that use these environments as habitat, including birds, mammals, and insects that have adapted to specific conditions.',
  'Subalpine Scrub climate change impacts: Expected to be sensitive to changes in temperature and precipitation patterns, with potential shifts in species composition and vegetation structure.',
  'Arctic Scrub remote sensing features: Characterized by distinctive spectral signatures in satellite images, often reflecting the sparse vegetation cover and patchy distribution of plant species.'],
 32: ['Temperate and Mediterranean-Montane Scrub is a type of vegetation found in southern Europe, characterized by a dominant cover of scrubby vegetation.',
  'This habitat is typically found on well-drained soils, often with rocky outcrops or steep slopes.',
  'The vegetation consists of a mix of deciduous and evergreen shrubs, including species such as juniper, oak, and pine.',
  'Mediterranean-Montane Scrub can be distinguished from other scrub habitats by its high diversity of plant species.',
  'This habitat supports a wide range of wildlife, including birds, mammals, and insects.',
  'The scrub vegetation often forms dense thickets, with a layered structure composed of different height classes.',
  'Juniper (Juniperus communis) is a dominant shrub in this habitat, often forming dense stands.',
  'Oak (Quercus spp.) is another common species, often found on well-drained soils.',
  'Pine (Pinus spp.) is also present, particularly in areas with more acidic soils.',
  'Mediterranean-Montane Scrub can be divided into sub-habitats based on soil type and moisture levels.',
  'This habitat supports a range of land cover types, including grasslands, wet meadows, and rocky outcrops.',
  'The climate is generally mild, with cool winters and warm summers.',
  'Precipitation is typically high in winter months, with some areas receiving over 1,000 mm per year.',
  'Vegetation in Mediterranean-Montane Scrub can be sparse and patchy, particularly in drier areas.',
  'This habitat supports a range of tree species, including oak, beech, and pine.',
  'The scrub vegetation often forms a mosaic of different plant species, with some areas dominated by one species while others are more diverse.',
  'Mediterranean-Montane Scrub can be affected by human activities such as agriculture, urbanization, and forestry.',
  'This habitat is often found on south-facing slopes, which receive high levels of solar radiation.',
  'The vegetation in this habitat can be influenced by the surrounding landscape, with some areas forming part of larger ecosystems.',
  'Mediterranean-Montane Scrub supports a range of wildlife, including the European tortoise and the Iberian lynx.',
  'This habitat is often characterized by a high level of endemism, with many species found nowhere else in Europe.',
  'Vegetation in Mediterranean-Montane Scrub can be influenced by soil type, with some areas forming acid soils while others are more alkaline.',
  'The scrub vegetation often forms dense mats on the ground, which can act as a habitat for small animals.',
  'This habitat supports a range of insect species, including bees and butterflies.',
  'Mediterranean-Montane Scrub can be managed through conservation efforts such as habitat restoration and reforestation programs.'],
 40: ['A shrub plantation is a type of land use characterized by dense stands of woody vegetation, typically comprising species such as blackthorn (Prunus spinosa) and gorse (Ulex europaeus).',
  'These ecosystems are commonly found in Mediterranean coastal areas, where climate conditions favor the growth of drought-tolerant shrubs.',
  'Shrub plantations often exhibit a uniform canopy layer, with individual plants spaced at regular intervals to maximize density.',
  'In some cases, the ground layer may be dominated by grasses or other herbaceous vegetation.',
  'The use of prescribed burning as a management technique is common in shrub plantations to control fuel loads and promote regeneration.',
  'Shrub plantations can provide habitat for a variety of wildlife species, including birds (e.g., the Dartford Warbler) and small mammals.',
  'In aerial images, these ecosystems are often characterized by a dense, greyish-brown color due to the dominance of shrubs over grasses or other vegetation.',
  'Shrub plantations may cover large areas, sometimes spanning hundreds of hectares.',
  'These ecosystems can be found in a variety of climates, but are most common in Mediterranean and subtropical regions.',
  'The structure of shrub plantations can vary depending on factors such as soil type and land use history.',
  'In some cases, shrubs may be planted in rows or in a grid pattern to facilitate harvesting or grazing.',
  'Shrub plantations can provide important ecosystem services, including carbon sequestration and water filtration.',
  'The dominant shrub species can vary depending on the region and climate conditions.',
  'In aerial images, shrub plantations often exhibit a characteristic "mown" appearance due to regular mowing or grazing practices.',
  'Shrub plantations may be managed for timber production, although this is less common in some regions.',
  'These ecosystems can provide important habitat for pollinators and other beneficial insects.',
  'In some cases, shrub plantations may be subject to invasive species management due to the presence of non-native vegetation.',
  'Shrub plantations are often characterized by a lack of tree cover, although this can vary depending on land use history and management practices.',
  'The density of shrubs in these ecosystems can range from low (e.g., 1-5 plants per square meter) to high (e.g., >50 plants per square meter).',
  'Shrub plantations may be used for conservation purposes, including the protection of rare or endangered species.',
  'In some regions, shrub plantations are managed as a form of agroforestry, integrating livestock grazing with tree and shrub production.',
  'The age structure of shrub plantations can vary depending on factors such as land use history and management practices.',
  'Shrub plantations may be characterized by a lack of woody debris, although this can vary depending on the management practices employed.',
  'In aerial images, shrub plantations often exhibit a characteristic " patchwork" appearance due to the irregular distribution of individual plants.'],
 41: ['Broadleaved deciduous woodland is a temperate forest characterized by an understory dominated by broadleaf tree species.',
  'The canopy layer is typically composed of deciduous trees such as oak, beech, and ash, with leaf litter covering the forest floor.',
  'This habitat type is often associated with a mixture of herbaceous plants, including ferns, wild garlic, and bluebells.',
  'Broadleaved deciduous woodland can be identified by its scattered tree gaps and uneven canopy structure.',
  'The understory layer is often dominated by shrubs such as hazel, hawthorn, and blackthorn.',
  'Aerial surveys may reveal a mosaic of open clearings, copses, and woodland edges.',
  'Broadleaved deciduous woodland is often found in areas with well-drained soils and a moderate climate.',
  'The forest floor can be carpeted with a thick layer of leaf litter, creating a dense and humid environment.',
  'This habitat type supports a wide range of plant species, including orchids, wildflowers, and mosses.',
  'Broadleaved deciduous woodland is often characterized by a mix of tree species, with some trees being younger than others.',
  'The canopy layer can be dominated by single-species stands or mixed-species woodlands.',
  'Woodland edges may exhibit a distinct transition zone between the forest and surrounding landscape.',
  'Broadleaved deciduous woodland can be found in areas with a history of human activity, such as old agricultural fields.',
  'This habitat type is often associated with a mix of ancient and recently planted trees.',
  'The understory layer can be dense and impenetrable, making it difficult for large animals to move through.',
  'Broadleaved deciduous woodland supports a wide range of invertebrate species, including insects and arachnids.',
  'Woodland floors may exhibit a variety of tree stumps, roots, and other woody debris.',
  'This habitat type can be identified by its lack of dominant coniferous tree species.',
  'Broadleaved deciduous woodland often exhibits a mix of deciduous and evergreen shrubs in the understory layer.',
  'The canopy layer may display signs of disturbance, such as gaps or scarring caused by lightning strikes.',
  'Woodland edges can be characterized by a mosaic of different habitats, including grasslands and wetlands.',
  'Broadleaved deciduous woodland supports a wide range of bird species, including woodpeckers, warblers, and sparrows.',
  'The forest floor may exhibit a variety of signs of past management practices, such as ancient fence lines or old tracks.',
  'This habitat type can be identified by its uneven canopy structure and scattered tree gaps.',
  'Broadleaved deciduous woodland often exhibits a mix of open areas and dense woodland, creating a complex and dynamic landscape.'],
 43: ['Coniferous woodlands are temperate forests characterized by a predominantly coniferous tree layer, typically dominated by species such as spruce (Picea spp.), fir (Abies spp.), and pine (Pinus spp.).',
  'These forests cover approximately 10% of the European land area and are found in mountainous, subalpine, and boreal regions.',
  'Coniferous woodlands often exhibit a distinctive vertical structure, with taller trees towards the north-south aspect, creating an irregular canopy.',
  "The forest floor is typically covered by a dense layer of leaf litter, mosses, and lichens, reflecting the coniferous tree's needle litter accumulation.",
  'Conifers are often accompanied by shrubs such as heather (Erica spp.), bilberry (Vaccinium myrtillus), and crowberry (Empetrum nigrum).',
  'This forest type is characterized by a closed canopy, allowing only limited sunlight to penetrate, resulting in reduced understory vegetation diversity.',
  "Coniferous woodlands are often associated with acidic soils, particularly in the boreal zone, due to the conifers' high needle litter accumulation.",
  'The tree species composition of these forests can be influenced by factors such as climate change, human activities, and natural disturbances like wildfires.',
  'In mountainous regions, coniferous woodlands may exhibit a mixture of alpine and subalpine vegetation, with tree species such as spruce, fir, and pine dominating the landscape.',
  'Coniferous woodlands play a crucial role in maintaining water cycles, as they influence local precipitation patterns through evapotranspiration.',
  'The canopy layer of coniferous woodlands often exhibits a complex pattern of light and shadow, creating an irregular and dynamic microclimate.',
  'In these forests, the understory vegetation is typically dominated by herbaceous species such as ferns (Various spp.), grasses (Poaceae), and sedges (Carex).',
  'Coniferous woodlands can be divided into different subtypes based on factors like tree species composition, soil type, and climate.',
  'In boreal coniferous woodlands, the tree layer is often dominated by conifers such as spruce and fir, with a more open canopy structure.',
  'The forest floor of coniferous woodlands may be characterized by the presence of peat deposits, particularly in regions with high rainfall and low temperatures.',
  'Coniferous woodlands can serve as important habitats for various species, including birds (e.g., grouse, woodpeckers), insects (e.g., bark beetles), and mammals (e.g., deer, wolves).',
  'The composition of coniferous woodland tree layers can vary significantly depending on factors such as age structure, disturbance history, and climate conditions.',
  'Coniferous woodlands often exhibit a distinctive spatial pattern of tree distribution, which may be influenced by factors such as terrain shape, soil type, and aspect orientation.',
  'The understory vegetation of coniferous woodlands can be influenced by the presence of trees with different growth habits, such as shrubs and herbaceous species.',
  'Coniferous woodlands can be associated with various types of wetland habitats, including bogs, fens, and marshes, particularly in boreal regions.',
  'The tree layer composition of coniferous woodlands may change over time due to factors like climate change, forest management practices, or natural disturbances.',
  'Coniferous woodlands can be characterized by a variety of microclimates, including areas with high humidity, low temperatures, and limited sunlight.',
  "The canopy structure of coniferous woodlands can affect local weather patterns, such as creating an 'orographic effect' in mountainous regions.",
  'In boreal coniferous woodlands, the tree layer is often dominated by species such as black spruce (Picea mariana) and white spruce (Picea glauca).',
  'Coniferous woodlands can serve as important carbon sinks, storing significant amounts of carbon in trees and soils.'],
 44: ['A mixed deciduous and coniferous woodland is a temperate forest characterized by the coexistence of broadleaf and coniferous tree species.',
  'This woodland habitat typically features a diverse array of tree species, including oak, beech, and pine.',
  'The canopy layer of a mixed deciduous and coniferous woodland often exhibits a layered structure, with emergent trees such as oak or beech dominating the upper levels.',
  'A mix of deciduous and coniferous tree species creates a dynamic understory, where new growth and decay occur simultaneously.',
  'Mixed deciduous and coniferous woodlands are commonly found in temperate regions of Europe, particularly in areas with mild winters and warm summers.',
  'These woodlands can be identified by the presence of a diverse range of understory vegetation, including ferns, mosses, and wildflowers.',
  'The structure of a mixed deciduous and coniferous woodland can vary significantly depending on factors such as soil type and moisture levels.',
  'Mixed deciduous and coniferous woodlands often feature a characteristic "edge effect", where the transition from woodland to non-woodland habitat is marked by a zone of disturbed vegetation.',
  'This edge effect can be a key indicator of the age and health of the woodland, with younger and more dynamic systems exhibiting a greater degree of disturbance.',
  'Mixed deciduous and coniferous woodlands are home to a wide range of biodiversity, including birds, mammals, and invertebrates.',
  'The canopy layer of these woodlands can be dominated by species such as oak (Quercus robur) or beech (Fagus sylvatica).',
  'Coniferous tree species such as pine (Pinus sylvestris) or spruce (Picea abies) are often found in the upper levels of mixed deciduous and coniferous woodlands.',
  'Mixed deciduous and coniferous woodlands can be identified by the presence of characteristic features such as log jams, rock outcrops, and hollow logs.',
  'These features provide habitat for a range of wildlife, including insects, reptiles, and small mammals.',
  'The understory of mixed deciduous and coniferous woodlands is often characterized by a dense layer of vegetation, including ferns (e.g., Dryopteris spp.) and mosses (e.g., Sphagnum spp.).',
  'Mixed deciduous and coniferous woodlands are often found in areas with well-drained soils, such as sandstone or limestone outcrops.',
  'However, these woodlands can also be found on poorer soils, including clay or peat-based soils.',
  'The microclimate of mixed deciduous and coniferous woodlands can vary significantly depending on factors such as slope aspect and topography.',
  'These variations in microclimate can lead to a range of habitat types within the woodland, each supporting different communities of plants and animals.',
  'Mixed deciduous and coniferous woodlands are often found in areas with a history of human activity, including agriculture or forestry.',
  'However, these woodlands can also be found in areas that have been left untouched for centuries, providing habitat for a range of rare and threatened species.',
  'The structure of mixed deciduous and coniferous woodlands can be influenced by factors such as land use history and management practices.',
  'For example, older woodlands may exhibit a more closed canopy layer, while younger woodlands may have a more open structure.',
  'Mixed deciduous and coniferous woodlands can provide important ecosystem services, including carbon sequestration, water filtration, and soil stabilization.',
  'These ecosystems are often considered to be of high conservation value due to their rarity and the range of biodiversity they support.'],
 45: ['A line of trees, small anthropogenic woodland is a linear strip of woodland vegetation that has been created and maintained by human activities.',
  'These line-of-trees woodlands are typically found in temperate regions and are characterized by a narrow band of tree cover along the edge of agricultural land or urban areas.',
  'The species composition of these woodlands can vary widely, but common species include oak, ash, and beech.',
  'Line-of-trees woodlands often have a uniform canopy structure due to the regular spacing of trees.',
  'The understory is frequently dominated by herbaceous plants such as grasses and wildflowers.',
  'These small woodlands typically exhibit a mosaic pattern of tree cover and open fields or lawns.',
  'The lines of trees can be straight, curved, or irregular in shape due to human modification activities.',
  'Line-of-trees woodlands often have a patchwork appearance with varying densities of tree cover.',
  'The average tree height in these woodlands is typically between 10-20 meters.',
  'Canopy gaps are common due to the regular spacing of trees, allowing sunlight to filter through.',
  'These woodlands can provide habitat for a variety of wildlife species, including birds, insects, and small mammals.',
  'Line-of-trees woodlands often exhibit unique soil conditions due to human activities such as fertilization or irrigation.',
  'The soil type varies depending on the underlying geology but is often sandy loam or clay-loam.',
  'Vegetation cover in these woodlands can include trees, shrubs, and herbaceous plants.',
  'Line-of-trees woodlands are commonly found in urban and peri-urban areas of Europe.',
  'They are often used as green corridors for wildlife migration and habitat connectivity.',
  'The density of tree cover varies depending on factors such as climate, soil type, and land use history.',
  'These woodlands can exhibit a range of ages, from young (less than 50 years old) to mature (over 100 years old).',
  'Human activities such as pruning or thinning are common practices in line-of-trees woodlands.',
  'Line-of-trees woodlands often have a relatively low species richness due to the regular spacing of trees.',
  'The presence of tree gaps allows for increased biodiversity and habitat diversity.',
  'Canopy cover varies with the time of year, with more dense cover during winter months.',
  'Line-of-trees woodlands can be used as indicators of land use history and management practices.',
  'These small woodlands often exhibit unique adaptations to local climate conditions such as drought tolerance or cold hardiness.',
  'The aesthetic value of line-of-trees woodlands lies in their unique appearance, which provides a striking visual contrast to surrounding agricultural landscapes.'],
 47: ['The screes are rocky outcrops formed by the erosion of limestone and dolomite rocks, typically located at the headwaters of rivers.',
  'These areas often exhibit a mix of grasslands, scrublands, and heathlands, with a dominance of low-growing vegetation such as grasses and wildflowers.',
  'The characteristic visual feature of screes is their steep, rocky slopes, often with overhanging ledges and outcrops.',
  'In aerial images, screes can be identified by their distinctive patchwork pattern of grasslands, scrublands, and heathlands.',
  'The land cover of screes is typically dominated by limestone and dolomite rocks, with occasional patches of soil and vegetation.',
  'The climate of screes is generally cool and wet, with significant rainfall throughout the year.',
  'These areas support a variety of plant species, including grasses, wildflowers, and scrub plants such as gorse and bracken.',
  'The fauna of screes includes a range of invertebrates, such as beetles, flies, and spiders, as well as birds such as lapwings and curlew.',
  'Screes often have a unique microclimate, with cold air pools forming in the lee of the rocks and warm air rising to create convection currents.',
  'The geological history of screes is complex, involving periods of uplift, erosion, and deposition over millions of years.',
  'These areas can be found in various parts of Europe, including the UK, Ireland, and France, as well as other regions with similar geology.',
  'Screes are often characterized by a lack of trees, due to the harsh climate and poor soil quality.',
  'The vegetation of screes is adapted to the dry, sandy soils that dominate these areas, with species such as sedges and grasses dominating the landscape.',
  'In some cases, screes can be found in association with limestone caves and other karst features.',
  'These areas are often fragmented by streams and rivers, which have carved out valleys and created distinct microhabitats.',
  'The soil chemistry of screes is typically alkaline, due to the high levels of calcium carbonate from the underlying rocks.',
  'Screes can be affected by human activities such as land use changes, mining, and climate change.',
  'The unique combination of geology, climate, and vegetation makes screes a valuable area for scientific research and conservation.',
  'These areas provide habitat for a range of rare and endangered species, including plants and animals adapted to the harsh conditions.',
  'Screes can be used as indicators of environmental health, providing information on soil quality, water chemistry, and biodiversity.',
  'The cultural significance of screes is also significant, with many areas having historical or spiritual importance.',
  'These areas are often used for recreation, such as hiking, birdwatching, and rock climbing.',
  'Screes can be found in a range of landscape positions, including valley heads, river valleys, and coastal cliffs.',
  'The unique geological features of screes, such as overhanging ledges and arches, create complex habitats that support a variety of plant and animal species.',
  'Overall, the combination of geology, climate, and vegetation makes screes a fascinating and ecologically important habitat in Europe.'],
 48: ['Inland cliffs are linear or isolated rocky formations that rise abruptly from the surrounding terrain, often forming distinct boundaries between different landforms.',
  'Rock pavements are extensive areas of exposed bedrock, typically composed of granitic or metamorphic rocks, covering large tracts of land with little vegetation.',
  'Outcrops are individual rocky protrusions or patches of bedrock that break through the soil surface, often displaying distinctive geological features such as joints or foliation.',
  'Inland cliffs can be found in a variety of landscapes, including heathlands, grasslands, and agricultural areas, and may be surrounded by a ring of trees or shrubs.',
  'Rock pavements often exhibit unique landforms, such as "clints" (flat-topped rocks) and "grykes" (steep-sided rock faces), which are shaped by weathering and erosion processes.',
  'Inland cliffs can provide habitat for a range of plant species, including rare and endangered flora, such as heather and gorse.',
  'Outcrops may display striking visual features, such as colourful mineral deposits or unusual rock formations like "hoodoos" or "arêtes".',
  'Rock pavements often have little to no vegetation due to the harsh conditions and lack of soil, but may support microclimates that foster unique biodiversity.',
  'Inland cliffs can be an important feature in agricultural landscapes, providing boundaries between fields and helping to manage soil erosion.',
  'Outcrops are a common geological feature in areas where there has been tectonic activity, such as fault zones or volcanic regions.',
  'Rock pavements may exhibit evidence of past glaciation, such as "drumlins" (elongated hills formed by glacial deposits) or " striations" (scratches on the rock surface).',
  'Inland cliffs can be used for recreation, such as hiking, rock climbing, and picnicking, offering scenic views and access to unique geological features.',
  'Outcrops may support a range of microfauna, including insects and reptiles, that are adapted to living in rocky environments.',
  'Rock pavements often exhibit distinctive colour patterns, such as "foliation" (bands of different minerals) or "sheeting" (layers of rock).',
  'Inland cliffs can be an important feature in landscape evolution, helping to shape the surrounding terrain and influencing local hydrology.',
  'Outcrops may display unique landforms, such as "cairns" (rocky outcrops formed by wind or water erosion) or "kames" (small hills formed by glacial deposits).',
  'Rock pavements often have a high level of geological interest, with many displaying complex rock structures and mineral deposits.',
  'Inland cliffs can provide habitat for a range of animal species, including birds, mammals, and insects, that are adapted to living in rocky environments.',
  'Outcrops may exhibit evidence of human activity, such as ancient settlements or mining operations.',
  'Rock pavements often have limited vegetation due to the harsh conditions and lack of soil, but may support unique microclimates that foster biodiversity.',
  'Inland cliffs can be an important feature in cultural heritage landscapes, providing scenic views and access to historical sites.',
  'Outcrops are a common geological feature in areas with high levels of tectonic activity, such as fault zones or volcanic regions.',
  'Rock pavements may display striking visual features, such as "foliation" (bands of different minerals) or "sheeting" (layers of rock).',
  'Inland cliffs can be used for conservation efforts, helping to protect rare plant and animal species that are adapted to living in rocky environments.',
  'Outcrops often have a high level of aesthetic appeal, with many displaying unique visual features that make them popular among photographers and hikers.'],
 49: ['Alpine meadows: In European alpine meadows, low-lying areas are often covered with a mix of grasses and wildflowers, while steeper slopes are dominated by rocky outcrops and sparse vegetation.',
  'Tundra lakes: Tundra lakes in Europe are characterized by shallow water bodies with slow water currents, surrounded by patches of vegetation and rocky shores.',
  'Fjordic habitats: Fjords in Norway and Sweden support a diverse range of flora and fauna, including coniferous forests, glacier-dammed lakes, and steep rock walls.',
  'Glacier moraines: Glacier moraines are formed from accumulation of rocks and debris at the end of a retreating glacier, often featuring glacial lakes and distinctive U-shaped valleys.',
  'Arctic tundra wetlands: Arctic tundra wetlands in Europe are characterized by low-lying areas dominated by sedges and mosses, with scattered patches of lichens and grasses.',
  'Ice cap habitats: Ice caps in the European Alps support a limited range of flora and fauna, including alpine plants such as gentians and edelweiss, which thrive in harsh, cold conditions.',
  'Glacier valleys: Glacier valleys in the European Alps feature steep rock walls, slow-moving rivers, and diverse vegetation, including conifers and alpine grasses.',
  'Permafrost areas: Permafrost areas in Europe are characterized by permanently frozen soil, often featuring barren treeless landscapes and limited vegetation.',
  'Lapland forests: Lapland forests in Norway and Sweden support a unique range of flora and fauna adapted to the harsh Arctic climate, including conifers and lichens.',
  'Ice sheets: Ice sheets in Greenland and Iceland are formed from accumulation of snow and ice over thousands of years, often featuring distinct ridges and valleys.',
  'Cryocold water bodies: Cryocold water bodies in Europe are characterized by slow-moving rivers and lakes with low dissolved oxygen levels, supporting a limited range of aquatic life.',
  'Arctic tundra mires: Arctic tundra mires in Europe are formed from accumulation of peat and acidic water, often featuring unique vegetation such as caribou lichens.',
  'Snow-covered pine forests: Snow-covered pine forests in the European Alps feature coniferous trees with snow-encased branches, creating a distinctive white landscape.',
  'Glacier-dammed lakes: Glacier-dammed lakes in the European Alps are formed from accumulation of rocks and debris at the end of a retreating glacier, often featuring glacial moraines and U-shaped valleys.',
  'Arctic tundra heaths: Arctic tundra heaths in Europe are characterized by low-lying areas dominated by grasses and sedges, with scattered patches of lichens and mosses.',
  'Ice cap lakes: Ice cap lakes in the European Alps support a limited range of aquatic life, including fish and other organisms adapted to cold, oxygen-poor conditions.',
  'Cryogenic lake beds: Cryogenic lake beds in Europe are characterized by shallow water bodies with slow water currents, often featuring glacial moraines and rocky shores.',
  'Arctic tundra tussock grasslands: Arctic tundra tussock grasslands in Europe are formed from accumulation of grasses and sedges, often featuring unique vegetation such as caribou lichens.',
  'Glacier-carved valleys: Glacier-carved valleys in the European Alps feature steep rock walls, slow-moving rivers, and diverse vegetation, including conifers and alpine grasses.',
  'Snow-covered heathlands: Snow-covered heathlands in Europe are characterized by low-lying areas dominated by heathers and other acid-loving plants, with scattered patches of lichens and mosses.',
  'Arctic tundra boreal forests: Arctic tundra boreal forests in Europe support a unique range of flora and fauna adapted to the harsh Arctic climate, including conifers and lichens.',
  'Permafrost rivers: Permafrost rivers in Europe are characterized by slow-moving rivers with permanently frozen soil, often featuring glacial moraines and rocky shores.',
  'Ice sheet ridges: Ice sheet ridges in Greenland and Iceland are formed from accumulation of snow and ice over thousands of years, often featuring distinct ridges and valleys.',
  'Glacier-carved fjords: Glacier-carved fjords in Norway and Sweden feature steep rock walls, slow-moving rivers, and diverse vegetation, including conifers and alpine grasses.',
  'Arctic tundra peatlands: Arctic tundra peatlands in Europe are formed from accumulation of peat and acidic water, often featuring unique vegetation such as caribou lichens and sphagnum mosses.'],
 50: ['Bare rock outcrops in the Pyrenees Mountains, characterized by sparse scrub and limited biodiversity.',
  'A patchwork of bare earth and rocky outcrops in the Apennine Mountains, devoid of tree cover.',
  'A desolate area of compacted gravel and sand dunes in the Danube Delta, with limited vegetation growth.',
  'Exposed granite boulders and scattered scrub in the Scottish Highlands, with a low diversity of plant species.',
  'Areas of bare soil and sparse grasses on chalk downlands in southern England, supporting a unique set of flora.',
  'A featureless expanse of compacted sand and gravel in the Hungarian Puszta, with limited vegetation cover.',
  'Rocky outcrops and scrubby vegetation in the Carpathian Mountains, supporting a variety of rare plant species.',
  'Bare earth and rocky outcrops in the Apuseni Mountains, Romania, with limited tree cover and diverse shrub life.',
  'Compacted gravel and sand dunes in the Po Delta, Italy, with sparse vegetation growth.',
  'Areas of bare soil and sparse grasses on heathlands in northern England, supporting a unique set of flora.',
  'Exposed bedrock and sparse scrub in the Julian Alps, Slovenia, with limited biodiversity.',
  'A desolate area of compacted sand and gravel in the Vistula Delta, Poland, with limited vegetation cover.',
  'Rocky outcrops and sparse vegetation in the Dinaric Alps, Bosnia and Herzegovina, supporting a variety of rare plant species.',
  'Bare earth and rocky outcrops in the Carpathian Mountains, Ukraine, with limited tree cover and diverse shrub life.',
  'Compacted gravel and sand dunes in the Aegean Delta, Greece, with sparse vegetation growth.',
  'Areas of bare soil and sparse grasses on moorlands in northern Scotland, supporting a unique set of flora.',
  'Exposed granite boulders and scattered scrub in the Pyrenees National Park, France/Spain, with limited biodiversity.',
  'A featureless expanse of compacted sand and gravel in the Bug River Delta, Belarus, with limited vegetation cover.',
  'Rocky outcrops and sparse vegetation in the Balkan Mountains, Bulgaria, supporting a variety of rare plant species.',
  'Bare earth and rocky outcrops in the Transylvanian Alps, Romania, with limited tree cover and diverse shrub life.',
  'Compacted gravel and sand dunes in the Oder Delta, Germany/Czech Republic, with sparse vegetation growth.',
  'Areas of bare soil and sparse grasses on chalk downlands in southern France, supporting a unique set of flora.',
  'Exposed bedrock and sparse scrub in the Kamnik-Savinja Alps, Slovenia, with limited biodiversity.',
  'A desolate area of compacted sand and gravel in the Silesian Lowlands, Poland, with limited vegetation cover.',
  'Rocky outcrops and sparse vegetation in the Sudeten Mountains, Czech Republic/Germany, supporting a variety of rare plant species.'],
 52: ['Arable land and market gardens in Europe typically feature rectangular or square plots of land used for crop production, often bounded by wooden fences or stone walls.',
  'These areas often exhibit a mosaic of agricultural landscapes, with diverse crops such as wheat, barley, and sunflowers replacing native vegetation.',
  'Market gardens frequently display rows of neatly arranged trees, fruit bushes, and herb plants, indicating intensive cultivation and management practices.',
  'Aerial images reveal a patchwork of arable land and market gardens, with distinct differences in land cover and coloration between adjacent plots.',
  'These agricultural landscapes typically have a low to moderate level of biodiversity, with an emphasis on crop diversity and managed vegetation.',
  'The dominant land cover is grassland or pasture, with occasional woodlands or hedgerows providing habitat for wildlife.',
  'Arable land and market gardens in Europe often display intricate networks of irrigation canals, ditches, and waterways.',
  'Fences and boundaries are frequently marked by wooden posts or stone walls, which also serve as habitat features for birds and insects.',
  'The landscape is often dotted with farm buildings, such as barns, silos, and greenhouses, which reflect the intensity of agricultural production.',
  'Market gardens may incorporate ornamental elements, like ponds, fountains, or statues, to create visually appealing landscapes.',
  'Arable land in Europe typically has a gentle slope, allowing for efficient drainage and crop rotation.',
  'The use of conservation tillage and cover crops is often observed, reducing soil erosion and promoting soil health.',
  'Irrigation systems are frequently used to supplement natural rainfall, with canals, ditches, and pipes crisscrossing the landscape.',
  'Aerial images reveal a mix of modern and traditional agricultural practices, such as combine harvesters and horse-drawn plows.',
  'Hedgerows and woodlands provide habitat for a range of wildlife species, including birds, insects, and small mammals.',
  'Market gardens often incorporate permaculture principles, promoting biodiversity and efficient land use.',
  'The landscape is characterized by an array of crop types, such as wheat, barley, oats, and vegetables, arranged in diverse patterns.',
  'Farm buildings are frequently painted or clad in materials like wood or stone, adding to the visual appeal of the landscape.',
  'Canals and waterways play a crucial role in irrigation systems, with some areas displaying extensive networks of canals and ditches.',
  'Arable land and market gardens in Europe often have a mix of grasses and weeds, which are managed through herbicides or mechanical control.',
  'Fences and boundaries are sometimes adorned with decorative elements, such as wooden posts topped with finials or stone walls with intricate carvings.',
  'Market gardens frequently incorporate ponds and lakes, providing habitat for aquatic species and reflecting the landscape in still waters.',
  'The use of solar panels and wind turbines is becoming increasingly common on arable land and market gardens.',
  'Aerial images reveal a mosaic of different agricultural landscapes, including grasslands, pastures, and woodland edges.',
  'Arable land and market gardens in Europe often have a mix of old and new agricultural practices, with modern technologies complementing traditional methods.'],
 53: ['Almond orchards: Cultivated areas of almond trees (Prunus dulcis) in southern Europe, characterized by their sprawling canopies and fruiting branches.',
  'Bamboo groves: Mass plantations of bamboo (Bambusa spp.) in Mediterranean climates, often used for landscaping and erosion control.',
  'Citrus orchards: Intensive cultivation of citrus fruits (Citrus spp.) in warm, dry regions, featuring rows of neatly pruned trees.',
  'Community gardens: Shared plots of land used by local residents for growing their own produce, often incorporating native plants and wildlife habitats.',
  'Fruit tree parks: Large areas of deciduous fruit trees (e.g., apple, pear) with diverse species and cultivars, creating a complex canopy structure.',
  'Greenhouses: Glass-enclosed structures housing a variety of crops year-round, using climate control systems to maintain optimal growing conditions.',
  'Herb gardens: Cultivated collections of aromatic herbs (e.g., rosemary, thyme), often used for culinary and medicinal purposes.',
  'Home gardens: Individual plots of land used by households for growing fruits, vegetables, and flowers, reflecting local gardening traditions.',
  'Lavender fields: Extensive plantations of lavender (Lavandula angustifolia) in dry climates, prized for their fragrant blooms and oil production.',
  'Orchard meadows: Mixed grasslands underlain by wood waste or apple pomace, hosting a diverse array of wildflowers and insects.',
  'Orchards with native trees: Cultivated areas incorporating native tree species alongside domesticated fruit trees, promoting biodiversity and ecosystem services.',
  'Permaculture gardens: Regenerative designs combining multiple plant species to create a self-sustaining ecosystem, minimizing external inputs.',
  'Pine plantations: Monoculture forests of pine (Pinus spp.) in Mediterranean climates, used for timber production and windbreaks.',
  'Pollinator gardens: Cultivated areas designed to attract bees and other pollinators, incorporating native flowers and herbs.',
  'Pomona parks: Large public spaces featuring a variety of fruit trees and orchards, often used as recreational areas and events venues.',
  'Quarry top gardens: Vegetated slopes or terraces created on former quarries, providing habitats for local wildlife and scenic views.',
  'Rose gardens: Formal, ornamental landscapes centered around roses (Rosa spp.), often featuring walking paths, fountains, and statues.',
  'Vegetable gardens: Cultivated areas focused on growing a wide variety of vegetables, using diverse techniques such as intensive agriculture or biodynamic methods.',
  'Vineyards: Commercial wine grape cultivation in dry regions, characterized by neat rows of vines and careful viticulture practices.',
  'Woodland gardens: Integrating native tree species into cultivated landscapes, mimicking natural forest dynamics and supporting local biodiversity.',
  'Xeriscapes: Low-water landscaping designs using drought-tolerant plants (e.g., succulents, cacti), often incorporating hardscapes and efficient irrigation systems.',
  'Zonal orchards: Cultivated areas organized into distinct zones for different types of crops, such as fruit trees, berry bushes, or cut flowers.',
  'Agroforestry parks: Integrated landscapes combining trees with agricultural crops, promoting ecological interactions and synergies.',
  'Forest-fringed gardens: Perennial borders and lawns situated along forest edges, incorporating native species and managing ecosystem services.',
  'Hedgerows: Live border strips of shrubs (e.g., blackthorn, hawthorn) used for hedging, wildlife corridors, and landscaping in agricultural landscapes.'],
 54: ['Avenue lined with modern office buildings: A broad street lined with contemporary glass and steel skyscrapers, often with green roofs and public spaces.',
  'Medieval town square with half-timbered houses: A historic town center featuring wooden-framed buildings with ornate facades, surrounded by cobblestone streets.',
  'High-rise residential complex with balconies: A densely packed apartment building with many balconies, providing residents with outdoor living spaces.',
  'Rural farmstead with stone barns: A traditional country dwelling featuring weathered stone structures for agricultural use.',
  'Modern shopping mall with green walls: A large commercial center incorporating lush greenery into its design to enhance indoor air quality.',
  'Colonial-style government building with clock tower: A historic administrative office featuring a prominent clock tower and ornate neoclassical architecture.',
  'Sustainable community with solar panels: A model residential development incorporating renewable energy sources, such as solar panels, for reduced carbon emissions.',
  'Artisanal bakery with chimneys and tile roof: A traditional bakery showcasing a classic, rustic design with visible chimneys and terracotta tiles.',
  'Industrial site with warehouses and cranes: An area dedicated to manufacturing or storage, characterized by large warehouses, heavy machinery, and overhead cranes.',
  'Victorian-era town hall with intricate stonework: A historic civic building featuring ornate carvings and architectural details.',
  'Coastal resort with beachfront condos: A seaside complex of modern apartments designed to take advantage of ocean views and sea breezes.',
  'Old windmill with wooden blades and chimney: A traditional wind-powered mill, now repurposed as a museum or tourist attraction.',
  'Bustling street market with colorful stalls: A vibrant outdoor marketplace where local vendors sell fresh produce, crafts, and other goods.',
  'Neo-gothic cathedral with stained glass windows: A prominent place of worship characterized by dramatic, pointed arches and vibrant stained glass.',
  'Renaissance-style palace with ornate fountains: An impressive royal residence featuring elaborate water features and classical architectural elements.',
  'Abandoned factory with rusted machinery: A former industrial site now reclaimed by nature, with overgrown vegetation and crumbling infrastructure.',
  'Modern eco-village with passive solar design: An environmentally friendly community featuring buildings designed to harness natural light and heat.',
  'Traditional fishing village with wooden boats: A coastal settlement centered around watercraft and marine activities, often with a rustic, weathered aesthetic.',
  'Medieval monastery with cloister and gardens: A historic place of worship surrounded by tranquil green spaces and intricate stone carvings.',
  'Contemporary art gallery with large windows: A modern museum or exhibition space showcasing cutting-edge artwork through expansive glass walls.',
  'Industrial park with large storage silos: An area designated for logistics and distribution, characterized by massive warehouses and storage facilities.',
  'Rural village pub with thatched roof and garden: A traditional rural gathering place featuring a rustic atmosphere, outdoor seating areas, and lush gardens.',
  'Large-scale agricultural complex with greenhouses: An industrial farming operation utilizing advanced greenhouse technology to grow crops year-round.',
  'Modern sports stadium with retractable roof: A state-of-the-art venue for athletic competitions, featuring a versatile design that can accommodate various events.',
  'Colonial-era colonial house with gabled roof and shutters: A historic residence showcasing classic architectural elements from the early colonial period.'],
 55: ['Low-density buildings often exhibit irregular shapes and fragmented forms, deviating from the typical rectangular shape.',
  'These structures typically have limited floor area coverage, ranging from 500 square meters to 5 hectares per building.',
  'The low-density pattern can create a mosaic-like effect, with scattered buildings forming a patchwork landscape.',
  'Vegetation growth is often more prevalent in low-density areas due to reduced impervious surface cover.',
  'Buildings may feature irregular setbacks or irregularly shaped rooftops, adding visual complexity.',
  'Low-density developments can lead to the formation of "garden cities," where green spaces and parks are integrated into urban design.',
  'Open spaces and public squares become more prominent in low-density areas, fostering a sense of community.',
  'In some regions, low-density buildings are integrated with agricultural land or farmland, reducing urban sprawl.',
  'The absence of high-rise structures allows for a greater variety of building styles and architectural forms.',
  'Low-density developments often prioritize pedestrian-friendly design, promoting walkability and human-scale urbanism.',
  'Buildings may be surrounded by green corridors, connecting parks and natural areas to the surrounding landscape.',
  'The low-density pattern can create "eyesores" or visually unappealing sites due to overexposure of industrial or agricultural activities.',
  'In some cases, low-density buildings are located near rivers or coastlines, taking advantage of waterfront views and natural beauty.',
  'Building facades may feature large windows, balconies, or outdoor spaces, blurring the line between indoor and outdoor areas.',
  'Low-density developments can lead to a greater sense of privacy among residents, as individual homes or buildings are more spaced out.',
  'The irregular shape of low-density buildings creates opportunities for innovative landscaping and garden design.',
  'Parking lots and driveways may be smaller in size, allowing for more green space and reduced visual impact.',
  'Low-density areas often feature a mix of old and new buildings, reflecting the evolution of urban development over time.',
  'The absence of dense high-rise structures makes it easier to incorporate public art installations or street furniture into the design.',
  'In some regions, low-density developments are integrated with existing infrastructure, such as rail lines or highways.',
  'Buildings may be designed with passive solar heating and cooling in mind, maximizing natural light and ventilation.',
  'Low-density areas can serve as refuges for wildlife, providing habitat for urban birds and other species.',
  'The irregular shape of low-density buildings creates opportunities for skylights, clerestory windows, or other forms of natural lighting.',
  'In some cases, low-density developments are located in former industrial sites, transforming derelict landscapes into vibrant community spaces.',
  'Low-density buildings may incorporate sustainable design elements, such as rainwater harvesting systems or green roofs.'],
 56: ['A former open-pit copper mine in Portugal, characterized by a large excavated area with a distinctive polygonal shape, surrounded by native vegetation and with a few scattered wind turbines.',
  'An abandoned steel mill in Poland, featuring a network of rusty pipes and machinery, set amidst a landscape of reclaimed marshland and reforestation efforts.',
  'A lead-zinc mine in Romania, marked by a series of linear excavation trenches and waste heaps, dotted with scrubby vegetation and wildflowers.',
  'A former oil refinery in the Netherlands, recognizable by its distinctive chimney stacks and sprawling complex of storage tanks, set against a backdrop of wind farms and agricultural land.',
  'An iron ore mine in Sweden, featuring a prominent open pit surrounded by dense coniferous forest, with a few scattered wooden buildings and equipment left behind.',
  'A coal mining site in Germany, characterized by a large network of abandoned tunnels and shafts, overgrown with vegetation and punctuated by the occasional discarded machinery part.',
  'An aluminum smelter in France, marked by a distinctive smokestack and sprawling complex of production facilities, set amidst a landscape of agricultural fields and woodland edges.',
  'A copper-molybdenum mine in Spain, featuring a large excavated area with steep slopes and a few scattered wind turbines, surrounded by native vegetation and with a nearby abandoned village.',
  'An old lead smelter in Italy, recognizable by its crumbling brickwork and rusty machinery, set amidst a landscape of rolling hills and olive groves.',
  'A zinc-lead mine in Belgium, marked by a series of linear excavation trenches and waste heaps, dotted with scrubby vegetation and wildflowers.',
  'A steelworks site in the UK, featuring a sprawling complex of production facilities and storage tanks, surrounded by industrial parks and motorways.',
  'An abandoned copper mine in Greece, characterized by a large excavated area with steep slopes and a few scattered wind turbines, surrounded by native vegetation and with a nearby ancient ruin.',
  'A coal-fired power plant in Austria, recognizable by its distinctive chimney stack and sprawling complex of cooling towers, set amidst a landscape of forest edges and agricultural fields.',
  'An iron ore processing facility in Denmark, marked by a series of linear conveyor belts and storage tanks, set amidst a landscape of coastal dunes and salt marshes.',
  'A uranium mine in Czech Republic, featuring a large excavated area with steep slopes and a few scattered wind turbines, surrounded by native vegetation and with a nearby abandoned village.',
  'An aluminum smelter in Finland, characterized by a distinctive smokestack and sprawling complex of production facilities, set amidst a landscape of boreal forest and lakes.',
  'A copper mine in Slovenia, marked by a large excavated area with steep slopes and a few scattered wind turbines, surrounded by native vegetation and with a nearby ancient castle ruin.',
  'An abandoned lead smelter in Croatia, recognizable by its crumbling brickwork and rusty machinery, set amidst a landscape of rolling hills and olive groves.',
  'A zinc-lead mine in Switzerland, featuring a series of linear excavation trenches and waste heaps, dotted with scrubby vegetation and wildflowers.',
  'A steelworks site in Norway, featuring a sprawling complex of production facilities and storage tanks, surrounded by industrial parks and fjords.',
  'An old coal mine in Hungary, characterized by a large network of abandoned tunnels and shafts, overgrown with vegetation and punctuated by the occasional discarded machinery part.',
  'A uranium processing facility in Slovakia, marked by a series of linear conveyor belts and storage tanks, set amidst a landscape of forest edges and agricultural fields.',
  'An aluminum smelter in Ireland, recognizable by its distinctive chimney stack and sprawling complex of production facilities, set amidst a landscape of coastal dunes and salt marshes.',
  'A copper mine in Bulgaria, featuring a large excavated area with steep slopes and a few scattered wind turbines, surrounded by native vegetation and with a nearby abandoned village.',
  'An iron ore processing facility in Estonia, marked by a series of linear conveyor belts and storage tanks, set amidst a landscape of coastal dunes and salt marshes.'],
 57: ['The railway line through the Slovenian countryside features a mix of modern and historic tracks, lined with dense forests and pastures.',
  'A network of small roads and bike paths weaves through the rolling hills of Tuscany, Italy, supporting local agriculture and tourism.',
  'The highway system in Norway is designed to minimize environmental impact, featuring wide medians and extensive vegetation corridors.',
  "The airport in Budapest, Hungary, is a major hub with modern terminals and runways, surrounded by the Danube Bend's scenic landscape.",
  "A stretch of motorway in Portugal features a unique blend of old and new road surfaces, reflecting the country's rich history and economic development.",
  "The tram system in Porto, Portugal, uses a combination of overhead wires and underground tunnels to navigate the city's hilly terrain.",
  'The canal network in Amsterdam, Netherlands, is a UNESCO World Heritage Site, with many sections featuring historic locks and picturesque surroundings.',
  "A major highway in Poland passes through the Białowieża Forest, one of Europe's last remaining primeval forests.",
  'The airport in Copenhagen, Denmark, features a unique design with green roofs and extensive use of natural light.',
  'A series of small roads in rural Croatia wind their way through orchards and vineyards, supporting local food production.',
  'The highway system in Austria is known for its scenic routes, featuring the Alpine mountain ranges and picturesque valleys.',
  "The tram network in Prague, Czech Republic, uses a combination of overhead wires and underground tunnels to navigate the city's historic center.",
  "A stretch of motorway in Slovenia features a unique blend of modern and historic road surfaces, reflecting the country's cultural heritage.",
  'The airport in Athens, Greece, is a major hub with modern terminals and runways, situated on the Athens Coastal Plain.',
  'A network of bike paths and footbridges connects the islands of Venice, Italy, supporting tourism and local transportation.',
  'The highway system in Belgium features a unique blend of modern and historic roads, including the famous Grand Boulevards of Brussels.',
  "The tram system in Vienna, Austria, uses a combination of overhead wires and underground tunnels to navigate the city's historic center.",
  'A series of small roads in rural Germany wind their way through forests and farmland, supporting local agriculture and forestry.',
  'The airport in Dublin, Ireland, features a unique design with green roofs and extensive use of natural light.',
  "A stretch of motorway in Italy features a unique blend of modern and historic road surfaces, reflecting the country's rich cultural heritage.",
  'The highway system in Romania passes through the Carpathian Mountains, featuring scenic routes and picturesque valleys.',
  "The tram network in Budapest, Hungary, uses a combination of overhead wires and underground tunnels to navigate the city's hilly terrain.",
  'A network of bike paths and pedestrianized streets connects the historic center of Bruges, Belgium, supporting tourism and local commerce.',
  'The airport in Lisbon, Portugal, features a unique design with modern terminals and runways, situated on the Tagus River estuary.',
  'A series of small roads in rural France wind their way through vineyards and orchards, supporting local food production and wine tourism.']}

